// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.20.3
// source: pb_common/pb_common.proto

package pb_common

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ROUTE int32

const (
	ROUTE_ROUTE_NONE     ROUTE = 0    // EMPTY
	ROUTE_LOBBY_ECHO     ROUTE = 1001 // ECHO请求
	ROUTE_LOBBY_LOGIN    ROUTE = 1002 // 登录请求
	ROUTE_MATCH_ECHO     ROUTE = 2001 // ECHO请求
	ROUTE_MATCH_JOIN     ROUTE = 2002 // 加入匹配队列
	ROUTE_RPSGAME_ECHO   ROUTE = 3001 // ECHO请求
	ROUTE_RPSGAME_START  ROUTE = 3002 // 开始游戏
	ROUTE_RPSGAME_PLAY   ROUTE = 3003 // 玩家出拳
	ROUTE_RPSGAME_RESULT ROUTE = 3004 // 游戏结果
)

// Enum value maps for ROUTE.
var (
	ROUTE_name = map[int32]string{
		0:    "ROUTE_NONE",
		1001: "LOBBY_ECHO",
		1002: "LOBBY_LOGIN",
		2001: "MATCH_ECHO",
		2002: "MATCH_JOIN",
		3001: "RPSGAME_ECHO",
		3002: "RPSGAME_START",
		3003: "RPSGAME_PLAY",
		3004: "RPSGAME_RESULT",
	}
	ROUTE_value = map[string]int32{
		"ROUTE_NONE":     0,
		"LOBBY_ECHO":     1001,
		"LOBBY_LOGIN":    1002,
		"MATCH_ECHO":     2001,
		"MATCH_JOIN":     2002,
		"RPSGAME_ECHO":   3001,
		"RPSGAME_START":  3002,
		"RPSGAME_PLAY":   3003,
		"RPSGAME_RESULT": 3004,
	}
)

func (x ROUTE) Enum() *ROUTE {
	p := new(ROUTE)
	*p = x
	return p
}

func (x ROUTE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ROUTE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_common_pb_common_proto_enumTypes[0].Descriptor()
}

func (ROUTE) Type() protoreflect.EnumType {
	return &file_pb_common_pb_common_proto_enumTypes[0]
}

func (x ROUTE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ROUTE.Descriptor instead.
func (ROUTE) EnumDescriptor() ([]byte, []int) {
	return file_pb_common_pb_common_proto_rawDescGZIP(), []int{0}
}

var File_pb_common_pb_common_proto protoreflect.FileDescriptor

var file_pb_common_pb_common_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x62, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x5f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x62, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0xab, 0x01, 0x0a, 0x05, 0x52, 0x4f, 0x55, 0x54, 0x45,
	0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00,
	0x12, 0x0f, 0x0a, 0x0a, 0x4c, 0x4f, 0x42, 0x42, 0x59, 0x5f, 0x45, 0x43, 0x48, 0x4f, 0x10, 0xe9,
	0x07, 0x12, 0x10, 0x0a, 0x0b, 0x4c, 0x4f, 0x42, 0x42, 0x59, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e,
	0x10, 0xea, 0x07, 0x12, 0x0f, 0x0a, 0x0a, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x45, 0x43, 0x48,
	0x4f, 0x10, 0xd1, 0x0f, 0x12, 0x0f, 0x0a, 0x0a, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x4a, 0x4f,
	0x49, 0x4e, 0x10, 0xd2, 0x0f, 0x12, 0x11, 0x0a, 0x0c, 0x52, 0x50, 0x53, 0x47, 0x41, 0x4d, 0x45,
	0x5f, 0x45, 0x43, 0x48, 0x4f, 0x10, 0xb9, 0x17, 0x12, 0x12, 0x0a, 0x0d, 0x52, 0x50, 0x53, 0x47,
	0x41, 0x4d, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0xba, 0x17, 0x12, 0x11, 0x0a, 0x0c,
	0x52, 0x50, 0x53, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x10, 0xbb, 0x17, 0x12,
	0x13, 0x0a, 0x0e, 0x52, 0x50, 0x53, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c,
	0x54, 0x10, 0xbc, 0x17, 0x42, 0x26, 0x5a, 0x24, 0x64, 0x75, 0x65, 0x2d, 0x67, 0x61, 0x6d, 0x65,
	0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f,
	0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_common_pb_common_proto_rawDescOnce sync.Once
	file_pb_common_pb_common_proto_rawDescData = file_pb_common_pb_common_proto_rawDesc
)

func file_pb_common_pb_common_proto_rawDescGZIP() []byte {
	file_pb_common_pb_common_proto_rawDescOnce.Do(func() {
		file_pb_common_pb_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_common_pb_common_proto_rawDescData)
	})
	return file_pb_common_pb_common_proto_rawDescData
}

var file_pb_common_pb_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_common_pb_common_proto_goTypes = []interface{}{
	(ROUTE)(0), // 0: pb_common.ROUTE
}
var file_pb_common_pb_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_common_pb_common_proto_init() }
func file_pb_common_pb_common_proto_init() {
	if File_pb_common_pb_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_common_pb_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_common_pb_common_proto_goTypes,
		DependencyIndexes: file_pb_common_pb_common_proto_depIdxs,
		EnumInfos:         file_pb_common_pb_common_proto_enumTypes,
	}.Build()
	File_pb_common_pb_common_proto = out.File
	file_pb_common_pb_common_proto_rawDesc = nil
	file_pb_common_pb_common_proto_goTypes = nil
	file_pb_common_pb_common_proto_depIdxs = nil
}
