[cluster]
    # 集群节点配置
    [cluster.node]
        # 实例ID，节点集群中唯一。不填写默认自动生成唯一的实例ID
        id = ""
        # 编解码器。可选：json | proto
        codec = "proto"
[mysql]
    [mysql.user]
        # 数据库连接地址
        dsn    = "root:qwer1234@tcp(127.0.0.1:3306)/db_jokergamecenter?charset=utf8mb4&parseTime=True&loc=Local"
        active = 50
        idle   = 25
[locate]
    [locate.redis]
        # 客户端连接地址
        addrs = [
            "127.0.0.1:6379",
        ]
        # 数据库号
        db = 0
        # 用户名
        username = ""
        # 密码
        password = ""
        # 最大重试次数
        maxRetries = 3
        # key前缀
        prefix = "due"
[log]
    # 日志输出文件
    file = "./log/front.log"
    # 日志输出级别，可选：debug | info | warn | error | fatal | panic
    level = "debug"
    # 日志输出格式，可选：text | json
    format = "text"
    # 是否输出到终端
    stdout = true
    # 时间格式，标准库时间格式
    timeFormat = "2006/01/02 15:04:05.000000"
    # 堆栈的最低输出级别，可选：debug | info | warn | error | fatal | panic
    stackLevel = "error"
    # 文件最大留存时间，d:天、h:时、m:分、s:秒
    fileMaxAge = "2d"
    # 文件最大尺寸限制，单位（MB）
    fileMaxSize = 100
    # 文件切割方式
    fileCutRule = "day"
    # 是否启用调用文件全路径
    callerFullPath = true
    # 是否启用分级存储
    classifiedStorage = true
# zap日志组件。以下配置项如果不存在，则会使用log域中的默认配置项；如果均未配置，则会使用系统默认配置
[redis]
    [redis.main]
        addr         = "127.0.0.1:6379"
        password     = "qwer1234"
        db           = 0
        maxRetries   = 64
        poolSize     = 10
        minIdleConns = 5
        dialTimeout  = 300
        readTimeout  = 500
        writeTimeout = 500
[registry]
    [registry.consul]
        # 客户端连接地址，默认为127.0.0.1:8500
        addr = "127.0.0.1:8500"
        # 是否启用健康检查，默认为true
        healthCheck = true
        # 健康检查时间间隔（秒），仅在启用健康检查后生效，默认为10
        healthCheckInterval = 10
        # 健康检查超时时间（秒），仅在启用健康检查后生效，默认为5
        healthCheckTimeout = 5
        # 是否启用心跳检查，默认为true
        heartbeatCheck = true
        # 心跳检查时间间隔（秒），仅在启用心跳检查后生效，默认为10
        heartbeatCheckInterval = 10
        # 健康检测失败后自动注销服务时间（秒），默认为30
        deregisterCriticalServiceAfter = 30
# 配置中心
[config]
    # consul配置中心
    [config.consul]
        # 客户端连接地址
        addr = "127.0.0.1:8500"
        # 路径。默认为config
        path = "config"
        # 读写模式。可选：read-only | write-only | read-write，默认为read-only
        mode = "read-only"
