// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.20.3
// source: pb_lobby/pb_lobby.proto

package pb_lobby

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EchoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"` // 消息内容
}

func (x *EchoReq) Reset() {
	*x = EchoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lobby_pb_lobby_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoReq) ProtoMessage() {}

func (x *EchoReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lobby_pb_lobby_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoReq.ProtoReflect.Descriptor instead.
func (*EchoReq) Descriptor() ([]byte, []int) {
	return file_pb_lobby_pb_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *EchoReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type EchoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // 用户ID
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`  // 消息内容
}

func (x *EchoRes) Reset() {
	*x = EchoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lobby_pb_lobby_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRes) ProtoMessage() {}

func (x *EchoRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lobby_pb_lobby_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRes.ProtoReflect.Descriptor instead.
func (*EchoRes) Descriptor() ([]byte, []int) {
	return file_pb_lobby_pb_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *EchoRes) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EchoRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_lobby_pb_lobby_proto protoreflect.FileDescriptor

var file_pb_lobby_pb_lobby_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x62, 0x5f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2f, 0x70, 0x62, 0x5f, 0x6c, 0x6f,
	0x62, 0x62, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x5f, 0x6c, 0x6f,
	0x62, 0x62, 0x79, 0x22, 0x1b, 0x0a, 0x07, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x2d, 0x0a, 0x07, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42,
	0x25, 0x5a, 0x23, 0x64, 0x75, 0x65, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62,
	0x5f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_lobby_pb_lobby_proto_rawDescOnce sync.Once
	file_pb_lobby_pb_lobby_proto_rawDescData = file_pb_lobby_pb_lobby_proto_rawDesc
)

func file_pb_lobby_pb_lobby_proto_rawDescGZIP() []byte {
	file_pb_lobby_pb_lobby_proto_rawDescOnce.Do(func() {
		file_pb_lobby_pb_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_lobby_pb_lobby_proto_rawDescData)
	})
	return file_pb_lobby_pb_lobby_proto_rawDescData
}

var file_pb_lobby_pb_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_lobby_pb_lobby_proto_goTypes = []interface{}{
	(*EchoReq)(nil), // 0: pb_lobby.EchoReq
	(*EchoRes)(nil), // 1: pb_lobby.EchoRes
}
var file_pb_lobby_pb_lobby_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_lobby_pb_lobby_proto_init() }
func file_pb_lobby_pb_lobby_proto_init() {
	if File_pb_lobby_pb_lobby_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_lobby_pb_lobby_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lobby_pb_lobby_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_lobby_pb_lobby_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_lobby_pb_lobby_proto_goTypes,
		DependencyIndexes: file_pb_lobby_pb_lobby_proto_depIdxs,
		MessageInfos:      file_pb_lobby_pb_lobby_proto_msgTypes,
	}.Build()
	File_pb_lobby_pb_lobby_proto = out.File
	file_pb_lobby_pb_lobby_proto_rawDesc = nil
	file_pb_lobby_pb_lobby_proto_goTypes = nil
	file_pb_lobby_pb_lobby_proto_depIdxs = nil
}
